apiVersion: v1
kind: Pod
metadata:
  name: coreutils-test-pod-n{}
  labels:
    workload: test
  annotations:
    alpha.image.policy.openshift.io/resolve-names: '*'
spec:
  schedulerName: "{}"
  containers:
  - name: test-container
    image: load-aware/coreutils:make
    imagePullPolicy: IfNotPresent
    command: ["make", "test"]
    resources:
      requests:
        cpu: "100m"
  restartPolicy: Never
