apiVersion: v1
kind: Pod
metadata:
  name: coreutils-make-pod-n{}
  labels:
    workload: make
  annotations:
    alpha.image.policy.openshift.io/resolve-names: '*'
spec:
  schedulerName: "{}"
  containers:
  - name: make-container
    image: load-aware/coreutils:deps
    imagePullPolicy: IfNotPresent
    command: ["/bin/sh"]
    args: ["-c", "for i in {1..8}; do echo 'making' && make clean && make -j 1; done"]
    resources:
      requests:
        cpu: "100m"
  restartPolicy: Never
