apiVersion: v1
kind: Pod
metadata:
  name: sleep-pod-n{pod_index}
  labels:
    workload: sleep
  annotations:
    alpha.image.policy.openshift.io/resolve-names: '*'
spec:
  schedulerName: "{scheduler_name}"
  containers:
  - name: sleep-container
    image: registry.access.redhat.com/ubi8/ubi
    imagePullPolicy: IfNotPresent
    command: ["sleep", "{sleep_duration}"]
    resources:
      requests:
        cpu: "100m"
  restartPolicy: Never
